AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Pokedex

  Sample SAM Template for Pokedex

Resources:
  PokedexTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "PokemonNumber"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PokemonNumber"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

Outputs:
  PokedexTableName:
    Description: "Name of the DDB Table that holds the trainers"
    Value: !Ref PokedexTable
    Export:
      Name: "PokedexTableName"
  PokedexTableArn:
    Description: "ARN of the DDB Table that holds the trainers"
    Value: !GetAtt [PokedexTable, "Arn"]
    Export:
      Name: "PokedexTableArn"